# Generated by Django 2.2.7 on 2019-12-06 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customtext_dada'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='r1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customtext_r1', to='home.HomePage'),
        ),
    ]
